include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "flutter_sdk/**"
  errors:
    invalid_annotation_target: ignore
    flutter_style_todos: ignore
    sort_pub_dependencies: false
